version: '{branch}-{build}'

install:
  - "SET PATH=C:\\Python27-x64;C:\\Python27-x64\\Scripts;%PATH%"
  - "python --version"
  - "pip install tox==2.9.1"

# Build the binary after tests
build: false

test_script:
  - "tox -e py27,py34,py35,py36,flake8"
